namespace Vaporsoft.Akira;

/// <summary>
/// Snapshot of a running process. Maps to Win32_Process.
/// </summary>
public sealed class ProcessSnapshot
{
    /// <summary>Short description of the process.</summary>
    public string? Caption { get; init; }

    /// <summary>Name of the first concrete class in the inheritance chain.</summary>
    public string? CreationClassName { get; init; }

    /// <summary>Description of the process.</summary>
    public string? Description { get; init; }

    /// <summary>Path to the executable file of the process.</summary>
    public string? ExecutablePath { get; init; }

    /// <summary>Current operating condition of the process.</summary>
    public uint? ExecutionState { get; init; }

    /// <summary>Process identifier (same as ProcessId, as a string handle).</summary>
    public string? Handle { get; init; }

    /// <summary>Total number of open handles owned by the process.</summary>
    public uint? HandleCount { get; init; }

    /// <summary>Date and time the process was installed.</summary>
    public DateTime? InstallDate { get; init; }

    /// <summary>Time in 100-nanosecond units executing in kernel mode.</summary>
    public ulong? KernelModeTime { get; init; }

    /// <summary>Maximum working set size of the process in KB.</summary>
    public uint? MaximumWorkingSetSize { get; init; }

    /// <summary>Minimum working set size of the process in KB.</summary>
    public uint? MinimumWorkingSetSize { get; init; }

    /// <summary>Name of the process executable.</summary>
    public string? Name { get; init; }

    /// <summary>CreationClassName of the operating system.</summary>
    public string? OSCreationClassName { get; init; }

    /// <summary>Name of the operating system.</summary>
    public string? OSName { get; init; }

    /// <summary>Number of I/O operations performed that are not read or write.</summary>
    public ulong? OtherOperationCount { get; init; }

    /// <summary>Amount of data transferred in non-read/write I/O operations.</summary>
    public ulong? OtherTransferCount { get; init; }

    /// <summary>Number of page faults generated by the process.</summary>
    public uint? PageFaults { get; init; }

    /// <summary>Amount of page file space used by the process in KB.</summary>
    public uint? PageFileUsage { get; init; }

    /// <summary>Unique identifier of the process that created this process.</summary>
    public uint? ParentProcessId { get; init; }

    /// <summary>Peak amount of page file space used during the process's lifetime in KB.</summary>
    public uint? PeakPageFileUsage { get; init; }

    /// <summary>Peak virtual address space the process has used in bytes.</summary>
    public ulong? PeakVirtualSize { get; init; }

    /// <summary>Peak working set size of the process in KB.</summary>
    public uint? PeakWorkingSetSize { get; init; }

    /// <summary>Scheduling priority of the process.</summary>
    public uint? Priority { get; init; }

    /// <summary>Current number of pages allocated that are only accessible to this process.</summary>
    public ulong? PrivatePageCount { get; init; }

    /// <summary>Numeric identifier used to distinguish one process from another.</summary>
    public uint? ProcessId { get; init; }

    /// <summary>Quota of nonpaged pool usage for this process.</summary>
    public uint? QuotaNonPagedPoolUsage { get; init; }

    /// <summary>Quota of paged pool usage for this process.</summary>
    public uint? QuotaPagedPoolUsage { get; init; }

    /// <summary>Peak nonpaged pool usage quota for this process.</summary>
    public uint? QuotaPeakNonPagedPoolUsage { get; init; }

    /// <summary>Peak paged pool usage quota for this process.</summary>
    public uint? QuotaPeakPagedPoolUsage { get; init; }

    /// <summary>Number of read operations performed.</summary>
    public ulong? ReadOperationCount { get; init; }

    /// <summary>Amount of data read in bytes.</summary>
    public ulong? ReadTransferCount { get; init; }

    /// <summary>Terminal Services session identifier.</summary>
    public uint? SessionId { get; init; }

    /// <summary>Current status of the object.</summary>
    public string? Status { get; init; }

    /// <summary>Process termination date and time.</summary>
    public DateTime? TerminationDate { get; init; }

    /// <summary>Number of active threads in the process.</summary>
    public uint? ThreadCount { get; init; }

    /// <summary>Time in 100-nanosecond units executing in user mode.</summary>
    public ulong? UserModeTime { get; init; }

    /// <summary>Current size of the virtual address space the process is using in bytes.</summary>
    public ulong? VirtualSize { get; init; }

    /// <summary>Version of Windows in which the process is running.</summary>
    public string? WindowsVersion { get; init; }

    /// <summary>Amount of memory in bytes in the working set of this process.</summary>
    public ulong? WorkingSetSize { get; init; }

    /// <summary>Number of write operations performed.</summary>
    public ulong? WriteOperationCount { get; init; }

    /// <summary>Amount of data written in bytes.</summary>
    public ulong? WriteTransferCount { get; init; }
}
